# -*- coding: utf-8 -*-
"""plents.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LsYjpPwIAAK7YLavjEicvZ8dP21IhNdc
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv('exoTrain.csv')

df.head(5)

df=df.dropna()

df = df.drop_duplicates()

df['LABEL'] = df['LABEL'].apply(lambda x: 1 if x == 2 else 0)

df.to_csv('exoTrain_cleaned.csv', index=False)

X = df.drop(['LABEL'], axis=1)
y = df['LABEL']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rfc = RandomForestClassifier(n_estimators=100, random_state=42)

rfc.fit(X_train, y_train)

y_pred = rfc.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy*100)
print("Confusion Matrix:", conf_matrix)